// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooManagerApi.Data;

#nullable disable

namespace ZooManagerApi.Migrations
{
    [DbContext(typeof(ZooContext))]
    [Migration("20251121192206_RecriandoBancoCompleto")]
    partial class RecriandoBancoCompleto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZooManagerApi.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EspecieId")
                        .HasColumnType("int");

                    b.Property<int>("HabitatId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaisOrigem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("HabitatId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("ZooManagerApi.Models.Cuidado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Frequencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Cuidados");
                });

            modelBuilder.Entity("ZooManagerApi.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Especies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Leão"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Elefante"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Girafa"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Pinguim"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Tigre"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Urso"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Macaco"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Zebra"
                        });
                });

            modelBuilder.Entity("ZooManagerApi.Models.Habitat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Habitats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Savana"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Floresta Tropical"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Polar / Gelo"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Deserto"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Oceano"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Montanha"
                        });
                });

            modelBuilder.Entity("ZooManagerApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ZooManagerApi.Models.Animal", b =>
                {
                    b.HasOne("ZooManagerApi.Models.Especie", "Especie")
                        .WithMany("Animais")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooManagerApi.Models.Habitat", "Habitat")
                        .WithMany("Animais")
                        .HasForeignKey("HabitatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooManagerApi.Models.Usuario", "Usuario")
                        .WithMany("Animais")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Habitat");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZooManagerApi.Models.Cuidado", b =>
                {
                    b.HasOne("ZooManagerApi.Models.Animal", "Animal")
                        .WithMany("Cuidados")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("ZooManagerApi.Models.Animal", b =>
                {
                    b.Navigation("Cuidados");
                });

            modelBuilder.Entity("ZooManagerApi.Models.Especie", b =>
                {
                    b.Navigation("Animais");
                });

            modelBuilder.Entity("ZooManagerApi.Models.Habitat", b =>
                {
                    b.Navigation("Animais");
                });

            modelBuilder.Entity("ZooManagerApi.Models.Usuario", b =>
                {
                    b.Navigation("Animais");
                });
#pragma warning restore 612, 618
        }
    }
}
